rem vim:ft=dos
C:
del NHJR.EXE
cd TC
rem TCC.EXE -g3 -j3 -w -N -I. -L. -I..\INCLUDE -e..\NHJR.EXE ..\SRC\WORLD.C ..\SRC\INPUT.C ..\SRC\SCREEN.C ..\SRC\MAIN.C GRAPHICS.LIB
TCC.EXE -g3 -j3 -N -I. -L. -I..\INCLUDE -e..\NHJR.EXE ..\SRC\WORLD.C ..\SRC\INPUT.C ..\SRC\SCREEN.C ..\SRC\MAIN.C GRAPHICS.LIB
cd ..
rem NHJR.EXE
